### ISSUE TITLE
put upstream at Debian

### ISSUE THREAD

**Issue by adrelanos** [jonasmalacofilho/ubuntu-luks-suspend#1]
Could you take this upstream to Debian please?

**Comment by jonasmalacofilho** [comment]
Do you mean the issue or the (lack of) progress on solving it?

**Comment by adrelanos** [comment]
No. I am suggesting `ubuntu-luks-suspend` -> `luks-suspend` and getting one day `luks-suspend` installable from packages.debian.org. (From where it naturally flows down to Ubuntu and other Linux distributions.)

**Comment by jonasmalacofilho** [comment]
Hm, that's a good point, and that may be possible now that both Debian and Ubuntu are using the same init: systemd. However, there are other differences that need to be handled (both use the same init system, but not necessarily the same services or service configuration), and also Ubuntu's latest LTS release (14.04) still uses upstart.

In fact, since my Ubuntu machines are 14.04, I have some interest to keep this Ubuntu/upstart focused, at least until this actually works or the next Ubuntu LTS release (April 2016).

On a side note, my more bleeding edge boxes are using Arch, and for it [vianney/arch-luks-suspend](https://github.com/vianney/arch-luks-suspend) seems to do the trick.

**Comment by HulaHoopWhonix** [comment]
Hi any progress on this?

**Comment by jonasmalacofilho** [comment]
i haven't really looked into this in the last year... what debian version are you using?

**Comment by HulaHoopWhonix** [comment]
Personally I run testing but most of our user base is on Jessie (stable).

**Comment by jonasmalacofilho** [comment]
@HulaHoopWhonix @adrelanos I'm sorry but I honestly don't think I'll be able to work on this anytime soon.

Since (almost) everyone's using systemd these days, I would suggest trying to port [vianney/arch-luks-suspend](https://github.com/vianney/arch-luks-suspend) from scratch...

**Comment by jonasmalacofilho** [comment]
You could also check #2 for a solution that quite possibly _could_ work by now (assuming the kernel patches have been accepted and that nothing else has broken)...
